### ISSUE TITLE
CodeQL injectes -p:UserSharedCompilation=false into dotnet test causing a failure

### ISSUE THREAD

**Issue by PavelBansky** [microsoft/codeql#12]
When using sandwich mode, CodeQL is injecting `-p:UserSharedCompilation=false` into `dotnet test` command, even if the build is not required.

Repro steps:
`dotnet test PrimeService.Tests.dll` will fail in sandwich mode with error:
**The argument -p:UseSharedComilation=false is invalid. Please use the /help option to check the list of valid arguments.**

Easy repro steps without CodeQL:
`dotnet test PrimeService.Tests.dll -p:UseSharedComilation=false`
This will end with the same error
**The argument -p:UseSharedComilation=false is invalid. Please use the /help option to check the list of valid arguments.**

CodeQL needs to be more sensitive when injecting into `dotnet test`

**Comment by PavelBansky** [comment]
This issues was moved to: https://github.com/githubcustomers/microsoft-codeql-support/issues/70

**Comment by zacharydweiss** [comment]
@PavelBansky was this issue resolved? The issue returns 404.
